spring:
  application:
    name: order_service # Application name

  datasource:
    url: jdbc:mysql://localhost:3306/order_service_db # Database connection URL
    username: root # Database username
    password: mysql # Database password

  jpa:
    hibernate:
      ddl-auto: none # Hibernate DDL auto configuration
    show-sql: true # Enable SQL logging
    properties:
      hibernate:
        format_sql: true # Format SQL logs for better readability

server:
  port: 8081 # Server port

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        web: DEBUG # Enable detailed request logging
        enableLoggingRequestDetails : DEBUG
      hibernate:
        SQL: DEBUG # Set logging level for Hibernate SQL
        type:
          descriptor:
            sql: TRACE # Enable Hibernate SQL parameter logging

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      circuitBreaker:
        # Register the circuit breaker's health status with Spring Boot Actuator
        registerHealthIndicator: true
        # The size of the buffer that stores circuit breaker events (e.g., state transitions, successes, failures)
        eventConsumerBufferSize: 10
        # The threshold (in percentage) for the failure rate. If 50% or more calls fail, the circuit breaker opens.
        failureRateThreshold: 50
        # The minimum number of calls required before the circuit breaker can calculate the failure rate
        minimumNumberOfCalls: 5
        # If enabled, the circuit breaker will automatically move from OPEN to HALF_OPEN state after the wait duration
        automaticTransitionFromOpenToHalfOpenEnabled: true
        # The time the circuit breaker stays in the OPEN state before transitioning to HALF_OPEN
        waitDurationInOpenState: 5s
        # The number of calls allowed in the HALF_OPEN state to determine if the circuit should be closed again
        permittedNumberOfCallsInHalfOpenState: 3
        # The size of the sliding window used to record call results
        slidingWindowSize: 10
        # Specifies if the sliding window is based on the number of calls (COUNT_BASED) or time (TIME_BASED)
        slidingWindowType: COUNT_BASED

inventory-url: http://localhost:8082
product-url: http://localhost:8080

