spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
      username: root
      password: password
      authentication-database: admin

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      circuitBreaker:
        # Register the circuit breaker's health status with Spring Boot Actuator
        registerHealthIndicator: true
        # The size of the buffer that stores circuit breaker events (e.g., state transitions, successes, failures)
        eventConsumerBufferSize: 10
        # The threshold (in percentage) for the failure rate. If 50% or more calls fail, the circuit breaker opens.
        failureRateThreshold: 50
        # The minimum number of calls required before the circuit breaker can calculate the failure rate
        minimumNumberOfCalls: 5
        # If enabled, the circuit breaker will automatically move from OPEN to HALF_OPEN state after the wait duration
        automaticTransitionFromOpenToHalfOpenEnabled: true
        # The time the circuit breaker stays in the OPEN state before transitioning to HALF_OPEN
        waitDurationInOpenState: 5s
        # The number of calls allowed in the HALF_OPEN state to determine if the circuit should be closed again
        permittedNumberOfCallsInHalfOpenState: 3
        # The size of the sliding window used to record call results
        slidingWindowSize: 10
        # Specifies if the sliding window is based on the number of calls (COUNT_BASED) or time (TIME_BASED)
        slidingWindowType: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
